name: License

on: push

jobs:
  license-finder:
    name: License Finder

    strategy:
      matrix:
        package-manager: [maven]

    runs-on: ubuntu-20.04

    steps:
      - name: Set up License Finder
        run: sudo gem install license_finder

      - name: Check out repository
        uses: actions/checkout@v2

      - name: Check licenses
        run: |
          license_finder \
            --project-path=${{ matrix.package-manager }} \
            --decisions-file=doc/decisions.yml
